services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: atlas_user
      POSTGRES_PASSWORD: atlas_pass
      POSTGRES_DB: atlas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
