# Generated by Django 5.2.15 on 2026-07-15 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('data_validade', models.DateField()),
                ('dias_restantes', models.IntegerField()),
                ('classificacao', models.CharField(choices=[('VENCIDO', 'Vencido'), ('CRITICO', 'Critico'), ('ATENCAO', 'Atencao'), ('NORMAL', 'Normal')], max_length=20)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Analise de lote',
                'verbose_name_plural': 'Analises de lotes',
                'ordering': ['-data_analise', 'codigo_produto', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('VENCIDO', 'Vencido'), ('CRITICO', 'Critico'), ('ATENCAO', 'Atencao'), ('NORMAL', 'Normal')], max_length=20)),
                ('canal', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracao de alerta',
                'verbose_name_plural': 'Configuracoes de alerta',
                'ordering': ['classificacao', 'canal', 'destinatario'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('VENCIDO', 'Vencido'), ('CRITICO', 'Critico'), ('ATENCAO', 'Atencao'), ('NORMAL', 'Normal')], max_length=20)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.CharField(max_length=255)),
                ('analise_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.analiselote')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['enviado_em', '-id'],
            },
        ),
    ]
