# Generated by Django 5.2.16 on 2026-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analiselote',
            index=models.Index(fields=['lote', 'codigo_produto'], name='core_analis_lote_665e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='analiselote',
            index=models.Index(fields=['classificacao', 'data_analise'], name='core_analis_classif_7a3395_idx'),
        ),
        migrations.AddConstraint(
            model_name='analiselote',
            constraint=models.UniqueConstraint(fields=('lote', 'codigo_produto'), name='unique_analise_lote_codigo_produto'),
        ),
    ]
