# Generated by Django 5.2.17 on 2026-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analiselote_core_analis_lote_665e0e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiselote',
            name='data_analise',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
