# Generated by Django 5.2.16 on 2026-08-09 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_analiselote_data_analise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselote',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analiselote',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='analiselote',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analiselote',
            name='quantidade_inicial',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analiselote',
            name='unidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_nova', models.DecimalField(decimal_places=3, max_digits=12)),
                ('local_anterior', models.CharField(blank=True, max_length=100)),
                ('local_novo', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='core.analiselote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_lotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de lote',
                'verbose_name_plural': 'Historicos de lotes',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
