# Generated by Django 5.2.15 on 2026-07-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100)),
                ('nome_produto', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_validade', models.DateField()),
                ('local', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_validade', 'codigo_produto', 'lote'],
            },
        ),
    ]
