# Generated by Django 6.0.7 on 2026-07-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
